from app import db

class StudentProfile(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    starting_class = db.Column(db.String(32))
    education_level = db.Column(db.String(64))
    school = db.Column(db.String(128))
    state = db.Column(db.String(128))
    district = db.Column(db.String(128))
    city = db.Column(db.String(128))
    institution = db.Column(db.String(256))
    course = db.Column(db.String(128))
    branch = db.Column(db.String(128))
    location = db.Column(db.String(128))
    interests = db.Column(db.Text)
    career_goal = db.Column(db.String(128))
    study_stream = db.Column(db.String(64))
    target_career_id = db.Column(db.Integer, db.ForeignKey('career.id'))
    resume = db.Column(db.String(256))
    resume_name = db.Column(db.String(256))
    extracted_name = db.Column(db.String(128))
    extracted_email = db.Column(db.String(256))
    extracted_phone = db.Column(db.String(64))
    projects_text = db.Column(db.Text)
    extracted_skills_text = db.Column(db.Text)
    certifications_text = db.Column(db.Text)
    experience_text = db.Column(db.Text)
    skills = db.relationship('StudentSkill', backref='profile')
